interface Props {
  text: string
  /** 'gpt' = real OpenAI commentary; 'note' = bundled / non-model text */
  variant?: 'gpt' | 'note'
}

export default function Commentary({ text, variant = 'gpt' }: Props) {
  const isNote = variant === 'note'
  return (
    <div style={{ background: 'rgba(99,102,241,0.05)', border: '1px solid rgba(99,102,241,0.2)', borderRadius: 16, padding: '20px 24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
        <span style={{ fontSize: 16 }}>{isNote ? '📋' : '💬'}</span>
        <span style={{ fontWeight: 700, fontSize: 14, color: '#a5b4fc' }}>
          {isNote ? 'Narrative' : 'GPT-4o Analysis'}
        </span>
        <span style={{ fontSize: 10, padding: '3px 8px', borderRadius: 999, background: 'rgba(99,102,241,0.15)', color: '#818cf8', border: '1px solid rgba(99,102,241,0.3)', fontWeight: 600 }}>
          {isNote ? 'Sample copy' : 'AI Generated'}
        </span>
      </div>
      <p style={{ color: '#d1d5db', fontSize: 14, lineHeight: 1.8 }}>{text}</p>
      <p style={{ fontSize: 11, color: '#374151', marginTop: 12 }}>
        {isNote
          ? 'Bundled text for layout — not from OpenAI. Research only — not financial advice.'
          : 'Generated by GPT-4o using the regime status, RSI, and top SHAP feature. Research only — not financial advice.'}
      </p>
    </div>
  )
}
